(()=>{
 const c=window.ENTREGA_CONFIG||{},url=(c.supabaseUrl||'').replace(/\/$/,'')+'/functions/v1/shift-history';
 const q=id=>document.getElementById(id),msg=t=>q('historyStatus').textContent=t;
 const safe=t=>String(t??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
 const show=v=>v===undefined||v===null||v===''?'—':safe(v);
 let accessCode=sessionStorage.getItem('l5-access-code')||'';
 q('historyDate').value=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bogota',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 function accessView(){q('loginPanel').hidden=!!accessCode;q('signedIn').hidden=!accessCode;q('closeShift').disabled=!accessCode;q('signedEmail').textContent=''}
 function view(which){q('historyPanel').hidden=which!=='history';q('app').hidden=which==='history';q('editHeading').hidden=which==='history';q('tabs').hidden=which==='history';q('historyBtn').classList.toggle('active',which==='history');q('editorBtn').classList.toggle('active',which!=='history');if(which==='history')loadHistory()}
 q('historyBtn').onclick=()=>view('history');q('editorBtn').onclick=()=>view('editor');accessView();
 if(!c.supabaseUrl){q('loginPanel').hidden=true;msg('Pendiente de conectar la base de datos. Puedes preparar el turno, pero todavía no cerrarlo ni consultar el historial.');return}
 async function call(method,date,shift,payload){const qs=new URLSearchParams({date});if(shift)qs.set('shift',shift);let response=await fetch(url+'?'+qs,{method,headers:{'content-type':'application/json','x-access-code':accessCode},body:payload?JSON.stringify(payload):undefined,cache:'no-store'});let body=await response.json();if(!response.ok)throw new Error(body.error||'No se completó la solicitud.');return body}
 q('sendLink').onclick=async()=>{let value=q('loginEmail').value.trim();if(!value)return msg('Ingresa la clave de acceso.');accessCode=value;try{await call('GET',q('historyDate').value,'');sessionStorage.setItem('l5-access-code',accessCode);q('loginEmail').value='';accessView();msg('Acceso habilitado.')}catch(e){accessCode='';msg(e.message)}};
 q('signOut').onclick=()=>{accessCode='';sessionStorage.removeItem('l5-access-code');accessView();q('historyRows').innerHTML='';q('historyDetail').hidden=true;msg('Acceso cerrado.')};
 q('closeShift').onclick=async()=>{if(!accessCode)return msg('Ingresa la clave de acceso.');let s=state.shifts[active],date=s.date,shift=active+1;if(!date||!s.sender||!s.receiver||!s.skus[0]?.sku)return msg('Completa fecha, Entrega, Recibe y SKU 1 antes de cerrar.');if(cats.reduce((a,[k])=>a+(score(s[k])||0),0)>100.00001)return msg('La distribución supera 100 %.');q('closeShift').disabled=true;msg('Guardando entrega cerrada…');try{await call('POST',date,String(shift),{shift_date:date,shift_no:shift,payload:structuredClone(s)});q('historyDate').value=date;q('historyShift').value=String(shift);msg('Entrega cerrada. Ya está disponible en Historial.');view('history')}catch(e){msg(e.message)}finally{q('closeShift').disabled=false}};
 q('findHistory').onclick=loadHistory;q('historyDate').onchange=loadHistory;q('historyShift').onchange=loadHistory;
 async function loadHistory(){q('historyDetail').hidden=true;if(!accessCode){q('historyRows').innerHTML='';msg('Ingresa la clave para ver el historial.');return}try{let {data}=await call('GET',q('historyDate').value,q('historyShift').value);q('historyRows').innerHTML=data.length?data.map((r,i)=>`<button type="button" class="history-row" data-index="${i}"><strong>Turno ${r.shift_no}</strong><span>${show(r.payload.sender)} → ${show(r.payload.receiver)}</span><span>Cerrado: ${new Date(r.created_at).toLocaleString('es-CO',{timeZone:'America/Bogota'})}</span></button>`).join(''):'No hay entregas cerradas para esta fecha y turno.';q('historyRows').querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>showDetail(data[Number(b.dataset.index)]));msg(`${data.length} entrega${data.length===1?'':'s'} encontrada${data.length===1?'':'s'}.`)}catch(e){msg(e.message)}}
 function showDetail(r){let s=r.payload,ob=s.observations||{},pairs=[['Fecha',r.shift_date],['Turno',r.shift_no],['Entrega',s.sender],['Recibe',s.receiver],['Eficiencia turno',s.shift&&s.shift+' %'],['Eficiencia día',s.day&&s.day+' %'],['Meta mes',s.target&&s.target+' %'],['Eficiencia mes',s.month&&s.month+' %'],['Producción',s.prod&&s.prod+' %'],['P. operativos',s.op&&s.op+' %'],['Camb & San',s.change&&s.change+' %'],['P. equipos',s.equipment&&s.equipment+' %'],['P. ajenos',s.external&&s.external+' %'],['P. auxiliares',s.aux&&s.aux+' %'],['WUR lavadora',s.wur&&s.wur+' ml/bot'],['Ausentismo',s.absence],['Evento seguridad',s.safety],['Evento calidad',s.quality],['ACR',s.acr],['Días sin AT',s.days]];let skuRows=(s.skus||[]).filter((k,i)=>i===0||s.hasSku2).map((k,i)=>`<div><strong>SKU ${i+1}:</strong> ${show(k.sku)} · ${show(k.speed)} · Contenido neto ${show(k.net)} ml · Rechazo ${show(k.reject)} % · Merma ${show(k.waste)} L · Cajas ${show(k.boxes)} CF · CPP ${show(k.cpp)} % · CPP mes ${show(k.cppMonth)} %</div>`).join('');let notes=[['P. operativos',ob.op],['P. equipos',ob.equipment],['P. ajenos',ob.external],['P. auxiliares',ob.aux],['Camb & San',ob.change],['Diversey',ob.diversey],['QSE',s.qse]].map(([l,v])=>`<div class="history-note"><strong>${l}</strong><span>${show(v)}</span></div>`).join('');q('historyDetail').innerHTML=`<h3>Entrega cerrada · ${show(r.shift_date)} · Turno ${r.shift_no}</h3><button type="button" id="historyPhoto" class="primary">Descargar foto de esta entrega</button><div class="history-grid">${pairs.map(([l,v])=>`<div><small>${l}</small><strong>${show(v)}</strong></div>`).join('')}</div><h4>Programa del día</h4>${skuRows}<h4>Observaciones</h4>${notes}`;q('historyDetail').hidden=false;q('historyPhoto').onclick=()=>window.exportShiftPNG(s,r.shift_no);q('historyDetail').scrollIntoView({behavior:'smooth',block:'start'})}
})();
